---
#Setting up on RedHat Systems
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

#Setting up on Debian Systems
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: start ntpd
  service: name=ntp enabled=yes state=started
  when: ansible_os_family == 'Debian'

- name: start ntpd
  service: name=ntpd enabled=yes state=started
  when: ansible_os_family == 'RedHat'

- name: setup ssh authorized keys
  include_tasks: add-ssh-keys.yml
  
