- name: updating apt cache
  apt: update_cache=yes

- name: installing common packages
  apt: name={{ item }} state=present
  with_items:
     - atop
     - bash-completion
     - emacs
     - htop
     - iotop
     - lsof
     - mosh
     - ntp
     - ntpdate
     - rsync
     - screen
     - sysstat
     - tmux
     - vim
