- name: installing common packages
  yum: name={{ item }} state=present
  with_items:
     - ntp
     - ntpdate
     - vim
     - emacs
     - atop
     - htop
     - sysstat
     - iotop
     - screen
     - tmux
     - bash-completion
     - rsync
